export const BRAND = {
  name: 'RentEase',
  tagline: 'Premium living. Flexible renting.',
};

export const NAV_LINKS = [
  { label: 'Home', to: '/' },
  { label: 'Explore', to: '/products' },
  { label: 'How It Works', to: '/#how-it-works' },
];

export const FOOTER_LINKS = {
  products: [
    { label: 'Furniture', to: '/products?category=furniture' },
    { label: 'Appliances', to: '/products?category=appliances' },
    { label: 'Electronics', to: '/products?category=electronics' },
    { label: 'Office', to: '/products?category=office' },
  ],
  company: [
    { label: 'About Us', to: '/' },
    { label: 'How it works', to: '/#how-it-works' },
    { label: 'Careers', to: '/' },
    { label: 'Press', to: '/' },
  ],
  support: [
    { label: 'Help Center', to: '/' },
    { label: 'Contact Us', to: '/' },
    { label: 'Track Order', to: '/dashboard' },
    { label: 'Returns & Pickup', to: '/' },
  ],
};

const image = (id) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1000&q=85`;

export const HERO_IMAGE = image('photo-1600210492486-724fe5c67fb0');

export const CATEGORIES = [
  {
    title: 'Furniture',
    description: 'Sofas, beds, tables, and everyday pieces for a home that feels like yours.',
    count: '100+ rentals',
    slug: 'furniture',
    image: image('photo-1555041469-a586c61ea9bc'),
  },
  {
    title: 'Appliances',
    description: 'Reliable essentials delivered ready to use, with maintenance included.',
    count: '100+ rentals',
    slug: 'appliances',
    image: image('photo-1571175443880-49e1d25b2bc5'),
  },
  {
    title: 'Electronics',
    description: 'Work-ready devices for study, entertainment, and life on the move.',
    count: '100+ rentals',
    slug: 'electronics',
    image: image('photo-1496181133206-80ce9b88a853'),
  },
  {
    title: 'Office',
    description: 'Thoughtful desks, chairs, and tools for better focused work.',
    count: '100+ rentals',
    slug: 'office',
    image: image('photo-1497366811353-6870744d04b2'),
  },
  {
    title: 'Bedroom',
    description: 'Comfort-first essentials for calmer nights and slower mornings.',
    count: '100+ rentals',
    slug: 'bedroom',
    image: image('photo-1505693416388-ac5ce068fe85'),
  },
  {
    title: 'Living Room',
    description: 'Layer your space with relaxed seating and pieces made for gathering.',
    count: '100+ rentals',
    slug: 'living-room',
    image: image('photo-1540574163026-643ea20ade25'),
  },
  {
    title: 'Kitchen',
    description: 'Dining and cooking essentials that make everyday hosting effortless.',
    count: '100+ rentals',
    slug: 'kitchen',
    image: image('photo-1616486338812-3dadae4b4ace'),
  },
  {
    title: 'Study / Work From Home',
    description: 'Desks, ergonomic seating, and focused-work essentials for productive days anywhere.',
    count: '100+ rentals',
    slug: 'study-work-from-home',
    image: image('photo-1497215728101-856f4ea42174'),
  },
];

const productDefaults = {
  reviewCount: 0,
  availability: 'Available now',
  badge: 'Popular',
  badgeVariant: 'primary',
  deposit: 1999,
  deliveryDays: '3–5 days',
  condition: 'Like new',
  warranty: '6 months',
  rentalDurations: [1, 3, 6, 12],
  features: ['Free delivery and pickup', 'Maintenance included', 'Flexible renewal'],
  included: ['Professional delivery', 'Setup at your doorstep', 'Care and maintenance support'],
};

const makeProduct = (product) => {
  const primaryImage = product.image ?? image('photo-1555041469-a586c61ea9bc');
  const normalized = {
    ...productDefaults,
    ...product,
    monthlyPrice: product.monthlyPrice ?? Number(product.price?.replace(/[^\d]/g, '') || 0),
    image: primaryImage,
    gallery: product.gallery ?? [primaryImage, primaryImage, primaryImage],
  };
  return {
    ...normalized,
    securityDeposit: product.securityDeposit ?? normalized.deposit,
    includedItems: product.includedItems ?? normalized.included,
    deliveryInfo: product.deliveryInfo ?? normalized.deliveryDays,
  };
};

const CATALOG_CITIES = [
  'Bengaluru', 'Mumbai', 'Delhi NCR', 'Noida', 'Gurgaon', 'Hyderabad',
  'Chennai', 'Kolkata', 'Ahmedabad', 'Jaipur', 'Pune', 'Nagpur',
];

const CATALOG_AVAILABILITY = [
  'Available now', 'Available now', 'Available in 2 days', 'Limited availability',
];

const slugify = (value) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

const EXPANSION_CONFIG = [
  {
    category: 'Furniture',
    slug: 'furniture',
    subcategories: ['Sofas', 'Accent Chairs', 'Coffee Tables', 'Dining Tables', 'Media Consoles'],
    modifiers: ['Urban', 'Nordic', 'Heritage', 'Cove', 'Metro', 'Terra', 'Arc', 'Loft', 'Haven', 'Studio'],
    types: ['Sofa', 'Accent Chair', 'Coffee Table', 'Dining Table', 'Media Console'],
    base: 349,
    step: 115,
    images: [
      'photo-1493663284031-b7e3aefcae8f', 'photo-1586023492125-27b2c045efd7',
      'photo-1549497538-303791108f95', 'photo-1501045661006-fcebe0257c3f',
      'photo-1567016432779-094069958ea5', 'photo-1618221195710-dd6b41faaea6',
      'photo-1494438639946-1ebd1d20bf85', 'photo-1550226891-ef816aed4a98',
      'photo-1505693416388-ac5ce068fe85', 'photo-1555041469-a586c61ea9bc',
      'photo-1532372320572-cda25653f0f8', 'photo-1540574163026-643ea20ade25',
    ],
    descriptor: 'a thoughtfully proportioned piece with durable finishes and an easy, everyday silhouette',
  },
  {
    category: 'Appliances',
    slug: 'appliances',
    subcategories: ['Refrigerators', 'Washing Machines', 'Air Conditioners', 'Microwaves', 'Water Purifiers'],
    modifiers: ['CoolNest', 'SwiftWash', 'FreshLine', 'AirCare', 'HeatWave', 'PureFlow', 'CrispChef', 'HomePro', 'EcoSmart', 'DailyEase'],
    types: ['Refrigerator', 'Washing Machine', 'Split AC', 'Microwave Oven', 'Water Purifier'],
    base: 649,
    step: 165,
    images: [
      'photo-1571175443880-49e1d25b2bc5', 'photo-1584568694244-14fbdf83bd30',
      'photo-1626806787461-102c1bfaaea1', 'photo-1556911220-e15b29be8c8f',
      'photo-1585515320310-259814833e62', 'photo-1610557892470-a1e2d6f2e7d5',
      'photo-1586208958839-06c17cacdf08', 'photo-1584622650111-993a426fbf0a',
      'photo-1631669370384-3c3f6f5c39c1', 'photo-1556912173-3bb406ef7e77',
      'photo-1592924357228-91a4daadcfea', 'photo-1600566753086-00f18fb6b3ea',
    ],
    descriptor: 'a reliable home essential with practical controls, efficient performance, and easy maintenance',
  },
  {
    category: 'Electronics',
    slug: 'electronics',
    subcategories: ['Laptops', 'Monitors', 'Televisions', 'Speakers', 'Tablets'],
    modifiers: ['Pixel', 'Nova', 'View', 'Sound', 'WorkMate', 'Stream', 'Edge', 'Core', 'Bright', 'Connect'],
    types: ['Laptop', 'Monitor', 'Smart TV', 'Bluetooth Speaker', 'Tablet'],
    base: 499,
    step: 190,
    images: [
      'photo-1496181133206-80ce9b88a853', 'photo-1527443224154-c4a3942d3acf',
      'photo-1593642632823-8f785ba67e45', 'photo-1593359677879-a4bb92f829d1',
      'photo-1601944177325-f8867652837f', 'photo-1511707171634-5f897ff02aa9',
      'photo-1517336714731-489689fd1ca8', 'photo-1585790050230-5dd28404ccb9',
      'photo-1546435770-a3e426bf472b', 'photo-1499346030926-9a72daac6c63',
      'photo-1550745165-9bc0b252726f', 'photo-1542751371-adc38448a05e',
    ],
    descriptor: 'a dependable device selected for crisp performance, simple setup, and flexible everyday use',
  },
  {
    category: 'Office',
    slug: 'office',
    subcategories: ['Office Chairs', 'Work Desks', 'Bookshelves', 'Storage', 'Desk Lamps'],
    modifiers: ['Ergo', 'Axis', 'Focus', 'Forma', 'Proline', 'Craft', 'Elevate', 'Posture', 'Workwell', 'Executive'],
    types: ['Office Chair', 'Work Desk', 'Bookshelf', 'Filing Cabinet', 'Desk Lamp'],
    base: 299,
    step: 105,
    images: [
      'photo-1497366811353-6870744d04b2', 'photo-1497366754035-f200968a6e72',
      'photo-1497366216548-37526070297c', 'photo-1517245386807-bb43f82c33c4',
      'photo-1497215728101-856f4ea42174', 'photo-1524758631624-e2822e304c36',
      'photo-1542744173-8e7e53415bb0', 'photo-1516321318423-f06f85e504b3',
      'photo-1556761175-b413da4baf72', 'photo-1497366811353-6870744d04b2',
      'photo-1521737711867-e3b97375f902', 'photo-1531482615713-2afd69097998',
    ],
    descriptor: 'a focused-work essential with considered ergonomics, clean lines, and space for your routine',
  },
  {
    category: 'Bedroom',
    slug: 'bedroom',
    subcategories: ['Beds', 'Mattresses', 'Wardrobes', 'Bedside Tables', 'Dressers'],
    modifiers: ['Cloud', 'Haven', 'Restwell', 'Loom', 'Quiet', 'Nest', 'Dawn', 'Velvet', 'Sleep', 'Oak'],
    types: ['Queen Bed', 'Mattress', 'Wardrobe', 'Bedside Table', 'Dresser'],
    base: 399,
    step: 130,
    images: [
      'photo-1505693416388-ac5ce068fe85', 'photo-1560185008-b033106af5c3',
      'photo-1616486338812-3dadae4b4ace', 'photo-1558997519-83ea9252edf8',
      'photo-1594620302200-9a762244a156', 'photo-1586023492125-27b2c045efd7',
      'photo-1522771739844-6a9f6d5f14af', 'photo-1505693416388-ac5ce068fe85',
      'photo-1513694203232-719a280e022f', 'photo-1618220179428-22790b461013',
      'photo-1617104678098-de229db51175', 'photo-1567016432779-094069958ea5',
    ],
    descriptor: 'a comfort-first bedroom piece designed to make slower mornings and calmer nights feel effortless',
  },
  {
    category: 'Living Room',
    slug: 'living-room',
    subcategories: ['Sectional Sofas', 'Recliners', 'Side Tables', 'TV Units', 'Floor Lamps'],
    modifiers: ['Maison', 'Luxe', 'Solace', 'Vista', 'Ember', 'Sunday', 'Atelier', 'Grove', 'Gather', 'Gallery'],
    types: ['Sectional Sofa', 'Recliner', 'Side Table', 'TV Unit', 'Floor Lamp'],
    base: 449,
    step: 145,
    images: [
      'photo-1540574163026-643ea20ade25', 'photo-1555041469-a586c61ea9bc',
      'photo-1493663284031-b7e3aefcae8f', 'photo-1567016432779-094069958ea5',
      'photo-1507473885765-e6ed057f782c', 'photo-1532372320572-cda25653f0f8',
      'photo-1618221195710-dd6b41faaea6', 'photo-1549497538-303791108f95',
      'photo-1501045661006-fcebe0257c3f', 'photo-1598300042247-d088f8ab3a91',
      'photo-1586023492125-27b2c045efd7', 'photo-1600210492486-724fe5c67fb0',
    ],
    descriptor: 'a welcoming living-room anchor with relaxed proportions and a finish made for gathering',
  },
  {
    category: 'Kitchen',
    slug: 'kitchen',
    subcategories: ['Coffee Machines', 'Air Fryers', 'Induction Cooktops', 'Mixer Grinders', 'Dining Sets'],
    modifiers: ['Brew', 'Chef', 'Pantry', 'Crisp', 'Savor', 'Daily', 'Terra', 'Cookwell', 'Fresh', 'Table'],
    types: ['Coffee Machine', 'Air Fryer', 'Induction Cooktop', 'Mixer Grinder', 'Dining Set'],
    base: 249,
    step: 95,
    images: [
      'photo-1556911220-bff31c812dba', 'photo-1556912167-f556f1f39fdf',
      'photo-1600566753086-00f18fb6b3ea', 'photo-1495474472287-4d71bcdd2085',
      'photo-1515003197210-e0cd71810b5f', 'photo-1556911220-e15b29be8c8f',
      'photo-1600494603989-9650cf6ddd3d', 'photo-1556912173-3bb406ef7e77',
      'photo-1585515320310-259814833e62', 'photo-1547592180-85f173990554',
      'photo-1551183053-bf91a1d81141', 'photo-1606787366850-de6330128bfc',
    ],
    descriptor: 'a compact cooking companion with intuitive controls and a finish that belongs in a modern kitchen',
  },
  {
    category: 'Study / Work From Home',
    slug: 'study-work-from-home',
    subcategories: ['Study Desks', 'Ergonomic Chairs', 'Monitor Arms', 'Bookshelves', 'Task Lights'],
    modifiers: ['Focus', 'Campus', 'Workday', 'Creator', 'Scholar', 'Remote', 'Sprint', 'Quiet', 'Grid', 'Launch'],
    types: ['Study Desk', 'Ergonomic Chair', 'Monitor Arm', 'Bookshelf', 'Task Light'],
    base: 279,
    step: 120,
    images: [
      'photo-1497215728101-856f4ea42174', 'photo-1516321318423-f06f85e504b3',
      'photo-1542744173-8e7e53415bb0', 'photo-1497366754035-f200968a6e72',
      'photo-1524758631624-e2822e304c36', 'photo-1556761175-b413da4baf72',
      'photo-1531482615713-2afd69097998', 'photo-1497366216548-37526070297c',
      'photo-1517245386807-bb43f82c33c4', 'photo-1552664730-d307ca884978',
      'photo-1521737711867-e3b97375f902', 'photo-1497366811353-6870744d04b2',
    ],
    descriptor: 'a practical focus-zone essential that keeps your setup comfortable, tidy, and ready for deep work',
  },
];

const ADDITIONAL_CONFIGS = [
  {
    category: 'Furniture',
    slug: 'furniture-lifestyle',
    subcategories: ['2-Seater Sofas', '3-Seater Sofas', 'Shoe Racks', 'Wardrobes', 'Storage Cabinets'],
    modifiers: ['Alder', 'Briar', 'Cedar', 'Dune', 'Elm', 'Fjord'],
    types: ['2-Seater Sofa', '3-Seater Sofa', 'Shoe Rack', 'Wardrobe', 'Storage Cabinet'],
    base: 449,
    step: 135,
    priceSpan: 2300,
    descriptor: 'a well-made home piece with balanced proportions, durable materials, and an easy-to-style finish',
  },
  {
    category: 'Furniture',
    slug: 'furniture-social',
    subcategories: ['Recliners', 'Dining Chairs', 'Bar Stools', 'Benches', 'Ottomans'],
    modifiers: ['Harbor', 'Juniper', 'Kora', 'Linden', 'Marlow', 'Willow'],
    types: ['Recliner', 'Dining Chair', 'Bar Stool', 'Bench', 'Ottoman'],
    base: 399,
    step: 125,
    priceSpan: 2100,
    descriptor: 'a versatile furniture essential finished for comfortable daily use and effortless hosting',
  },
  {
    category: 'Appliances',
    slug: 'appliances-cooling',
    subcategories: ['Single-Door Refrigerators', 'Double-Door Refrigerators', 'Side-by-Side Refrigerators', 'Dryers', 'Air Coolers'],
    modifiers: ['Polar', 'Frostline', 'Glacier', 'Chillmate', 'Nordwind', 'Boreal'],
    types: ['Single-Door Refrigerator', 'Double-Door Refrigerator', 'Side-by-Side Refrigerator', 'Clothes Dryer', 'Air Cooler'],
    base: 699,
    step: 185,
    priceSpan: 3500,
    descriptor: 'a dependable home appliance with efficient performance, practical controls, and easy maintenance',
  },
  {
    category: 'Appliances',
    slug: 'appliances-care',
    subcategories: ['Air Purifiers', 'Vacuum Cleaners', 'Dishwashers', 'Geysers', 'Ceiling Fans'],
    modifiers: ['AeroPure', 'CleanSweep', 'Sparkle', 'WarmFlow', 'BreezeMax', 'Cirrus'],
    types: ['Air Purifier', 'Vacuum Cleaner', 'Dishwasher', 'Geyser', 'Ceiling Fan'],
    base: 499,
    step: 165,
    priceSpan: 3100,
    descriptor: 'a quiet, efficient home companion designed to make everyday care feel simpler',
  },
  {
    category: 'Electronics',
    slug: 'electronics-entertainment',
    subcategories: ['Projectors', 'Soundbars', 'Gaming Consoles', 'Printers', 'Routers'],
    modifiers: ['Cinebeam', 'Sonic', 'GameGrid', 'Printly', 'Meshline', 'Arcadia'],
    types: ['Projector', 'Soundbar', 'Gaming Console', 'Wireless Printer', 'Wi-Fi Router'],
    base: 599,
    step: 225,
    priceSpan: 4800,
    descriptor: 'a capable connected device selected for clear performance, simple setup, and flexible everyday use',
  },
  {
    category: 'Electronics',
    slug: 'electronics-creator',
    subcategories: ['Cameras', 'Keyboards', 'Mice', 'Headphones', 'Webcams'],
    modifiers: ['Lenscraft', 'Keysmith', 'Clicker', 'Auralis', 'Viewcam', 'SignalPro'],
    types: ['Mirrorless Camera', 'Mechanical Keyboard', 'Wireless Mouse', 'Noise-Cancelling Headphones', 'HD Webcam'],
    base: 399,
    step: 205,
    priceSpan: 4300,
    descriptor: 'a polished tech essential with thoughtful ergonomics, reliable connectivity, and room to create',
  },
  {
    category: 'Office',
    slug: 'office-teams',
    subcategories: ['Ergonomic Chairs', 'Executive Chairs', 'Visitor Chairs', 'Standing Desks', 'Meeting Tables'],
    modifiers: ['Apex', 'Boardwalk', 'Civic', 'Director', 'Summit', 'Verve'],
    types: ['Ergonomic Chair', 'Executive Chair', 'Visitor Chair', 'Standing Desk', 'Meeting Table'],
    base: 399,
    step: 145,
    priceSpan: 2300,
    descriptor: 'a professional workspace piece built around comfort, clean lines, and productive routines',
  },
  {
    category: 'Office',
    slug: 'office-tools',
    subcategories: ['Monitor Arms', 'Office Lamps', 'Whiteboards', 'Conference Accessories', 'Storage Cabinets'],
    modifiers: ['Pivot', 'Lumen', 'Canvas', 'Briefing', 'Archive', 'Huddle'],
    types: ['Monitor Arm', 'Office Lamp', 'Whiteboard', 'Conference Speaker', 'Storage Cabinet'],
    base: 299,
    step: 115,
    priceSpan: 1900,
    descriptor: 'a considered office tool that keeps work more organized, comfortable, and ready for collaboration',
  },
  {
    category: 'Bedroom',
    slug: 'bedroom-foundation',
    subcategories: ['Single Beds', 'Double Beds', 'King Beds', 'Dressing Tables', 'Mirrors'],
    modifiers: ['Sol', 'Mira', 'Nook', 'Serein', 'Crest', 'Mellow'],
    types: ['Single Bed', 'Double Bed', 'King Bed', 'Dressing Table', 'Full-Length Mirror'],
    base: 499,
    step: 155,
    priceSpan: 3300,
    descriptor: 'a comfort-first bedroom piece designed for calmer nights, useful storage, and slower mornings',
  },
  {
    category: 'Bedroom',
    slug: 'bedroom-details',
    subcategories: ['Chest of Drawers', 'Bedroom Benches', 'Lamps', 'Storage Furniture', 'Vanity Cabinets'],
    modifiers: ['Aura', 'Citrine', 'Drift', 'Eclipse', 'Luna', 'Meadow'],
    types: ['Chest of Drawers', 'Bedroom Bench', 'Bedside Lamp', 'Storage Unit', 'Vanity Cabinet'],
    base: 349,
    step: 120,
    priceSpan: 2400,
    descriptor: 'a refined bedroom detail with practical storage and a finish that makes a room feel settled',
  },
  {
    category: 'Living Room',
    slug: 'living-room-comfort',
    subcategories: ['Sofas', 'Recliners', 'Lounge Chairs', 'Rugs', 'Ottomans'],
    modifiers: ['Riviera', 'Paloma', 'Canto', 'Mosaic', 'Marina', 'Soleil'],
    types: ['Lounge Sofa', 'Recliner', 'Lounge Chair', 'Area Rug', 'Ottoman'],
    base: 499,
    step: 165,
    priceSpan: 3200,
    descriptor: 'a relaxed living-room anchor with inviting textures, generous comfort, and a finish made for gathering',
  },
  {
    category: 'Living Room',
    slug: 'living-room-accents',
    subcategories: ['TV Units', 'Coffee Tables', 'Side Tables', 'Bookshelves', 'Consoles'],
    modifiers: ['Monaco', 'Clover', 'Pebble', 'Folio', 'Reverb', 'Verona'],
    types: ['TV Unit', 'Coffee Table', 'Side Table', 'Bookshelf', 'Console Table'],
    base: 349,
    step: 135,
    priceSpan: 2500,
    descriptor: 'a welcoming accent with useful function, relaxed proportions, and a finish that layers beautifully',
  },
  {
    category: 'Kitchen',
    slug: 'kitchen-prep',
    subcategories: ['Refrigerators', 'Microwave Ovens', 'Induction Cooktops', 'Kitchen Storage', 'Dining Tables'],
    modifiers: ['Saffron', 'Basil', 'Zest', 'PantryPlus', 'Hearth', 'Indigo'],
    types: ['Compact Refrigerator', 'Microwave Oven', 'Induction Cooktop', 'Kitchen Storage Cabinet', 'Dining Table'],
    base: 349,
    step: 125,
    priceSpan: 2700,
    descriptor: 'a dependable kitchen companion with intuitive controls and a finish that belongs in a modern home',
  },
  {
    category: 'Kitchen',
    slug: 'kitchen-serve',
    subcategories: ['Water Purifiers', 'Dishwashers', 'Electric Kettles', 'Kitchen Carts', 'Storage Racks'],
    modifiers: ['Simmer', 'Whisk', 'Temper', 'Bloom', 'Toast', 'Pour'],
    types: ['Water Purifier', 'Dishwasher', 'Electric Kettle', 'Kitchen Cart', 'Storage Rack'],
    base: 299,
    step: 105,
    priceSpan: 2300,
    descriptor: 'a practical cooking and serving essential that makes everyday hosting feel more effortless',
  },
  {
    category: 'Study / Work From Home',
    slug: 'study-focus',
    subcategories: ['Study Desks', 'Ergonomic Chairs', 'Monitors', 'Laptops', 'Webcams'],
    modifiers: ['DeepWork', 'Noteflow', 'Deskline', 'Taskly', 'ScholarPro', 'FocusHub'],
    types: ['Study Desk', 'Ergonomic Chair', 'Monitor', 'Laptop', 'Webcam'],
    base: 399,
    step: 215,
    priceSpan: 4600,
    descriptor: 'a focused-work essential that keeps your setup comfortable, tidy, and ready for deep work',
  },
  {
    category: 'Study / Work From Home',
    slug: 'study-studio',
    subcategories: ['Microphones', 'Printers', 'Desk Lamps', 'Monitor Stands', 'Keyboard and Mouse Sets'],
    modifiers: ['StreamDesk', 'QuietZone', 'PixelDesk', 'VoiceLab', 'PageTurn', 'WorkNest'],
    types: ['USB Microphone', 'Wireless Printer', 'Desk Lamp', 'Monitor Stand', 'Keyboard and Mouse Set'],
    base: 299,
    step: 145,
    priceSpan: 3000,
    descriptor: 'a flexible home-office tool chosen for clear focus, simple setup, and comfortable everyday use',
  },
];

const categoryImagePools = Object.fromEntries(EXPANSION_CONFIG.map((config) => [config.category, config.images]));
const ALL_EXPANSION_CONFIG = [
  ...EXPANSION_CONFIG,
  ...ADDITIONAL_CONFIGS.map((config) => ({ ...config, images: categoryImagePools[config.category] })),
];

const generateExpandedProducts = () => ALL_EXPANSION_CONFIG.flatMap((config, configIndex) =>
  config.modifiers.flatMap((modifier, modifierIndex) =>
    config.types.map((type, typeIndex) => {
      const index = modifierIndex * config.types.length + typeIndex;
      const imageIndex = index % config.images.length;
      const monthlyPrice = config.base + ((index * config.step) % (config.priceSpan ?? 980)) + (typeIndex * 35);
      const badge = index % 13 === 0 ? 'Featured' : index % 7 === 0 ? 'New' : index % 5 === 0 ? 'Best Value' : 'Popular';
      const badgeVariant = badge === 'New' ? 'warning' : badge === 'Best Value' ? 'success' : 'primary';
      const id = `${config.slug}-${slugify(modifier)}-${slugify(type)}`;
      const variantLabel = {
        'living-room-vista-sectional-sofa': 'Living',
        'furniture-studio-coffee-table': 'Home',
        'electronics-workmate-laptop': 'Pro',
        'study-work-from-home-focus-bookshelf': 'Study',
      }[id];
      const productName = `${modifier}${variantLabel ? ` ${variantLabel}` : ''} ${type}`;
      return makeProduct({
        id,
        name: productName,
        category: config.category,
        subcategory: config.subcategories[typeIndex],
        description: `${productName} is ${config.descriptor}.`,
        image: image(config.images[imageIndex]),
        gallery: [
          image(config.images[imageIndex]),
          image(config.images[(imageIndex + 1) % config.images.length]),
          image(config.images[(imageIndex + 2) % config.images.length]),
        ],
        monthlyPrice,
        originalPrice: monthlyPrice + 275 + ((index * 67) % 525),
        rating: Number((4.1 + ((index * 7 + configIndex) % 9) / 10).toFixed(1)),
        reviewCount: 14 + ((index * 17 + configIndex * 11) % 148),
        city: CATALOG_CITIES[(index + configIndex * 2) % CATALOG_CITIES.length],
        availability: CATALOG_AVAILABILITY[(index + configIndex) % CATALOG_AVAILABILITY.length],
        badge,
        badgeVariant,
        deposit: Math.round(monthlyPrice * 2.5 / 100) * 100,
        deliveryDays: index % 4 === 0 ? '2–4 days' : '3–5 days',
        condition: index % 6 === 0 ? 'Brand new' : index % 4 === 0 ? 'Excellent' : 'Like new',
        warranty: typeIndex === 0 || config.category === 'Electronics' ? '12 months' : '6 months',
        newestRank: 1000 - (configIndex * 50 + index),
        specifications: {
          Brand: `${modifier} Select`,
          Dimensions: `${36 + typeIndex * 8} × ${24 + modifierIndex * 3} in`,
          Color: ['Sand', 'Graphite', 'Oak', 'Cloud', 'Stone'][index % 5],
          Condition: index % 6 === 0 ? 'Brand new' : 'Like new',
          Warranty: typeIndex === 0 || config.category === 'Electronics' ? '12 months' : '6 months',
        },
      });
    }),
  ),
);

const CORE_PRODUCTS = [
  makeProduct({
    id: 'luxe-cloud-sofa',
    name: 'Luxe Cloud Sofa',
    category: 'Living Room',
    subcategory: 'Sofas',
    description: 'A generous three-seater with deep cushions and a soft, tailored finish for easy entertaining.',
    image: image('photo-1555041469-a586c61ea9bc'),
    monthlyPrice: 1499,
    originalPrice: 2199,
    rating: 4.9,
    reviewCount: 128,
    city: 'Bengaluru',
    badge: 'Featured',
    badgeVariant: 'primary',
    deposit: 4499,
    specifications: { Brand: 'RentEase Select', Dimensions: '84 × 36 × 32 in', Color: 'Cloud grey', Condition: 'Like new', Warranty: '6 months' },
  }),
  makeProduct({
    id: 'vista-sectional-sofa',
    name: 'Vista Sectional Sofa',
    category: 'Living Room',
    subcategory: 'Sofas',
    description: 'A relaxed L-shaped sectional with washable covers and room for the whole weekend crew.',
    image: image('photo-1540574163026-643ea20ade25'),
    monthlyPrice: 1999,
    originalPrice: 2799,
    rating: 4.8,
    reviewCount: 96,
    city: 'Mumbai',
    badge: 'Best Seller',
    badgeVariant: 'success',
    deposit: 5999,
    specifications: { Brand: 'RentEase Select', Dimensions: '102 × 68 × 33 in', Color: 'Warm beige', Condition: 'Like new', Warranty: '6 months' },
  }),
  makeProduct({
    id: 'studio-coffee-table',
    name: 'Studio Coffee Table',
    category: 'Living Room',
    subcategory: 'Tables',
    description: 'A clean-lined oak coffee table with a lower shelf for books, remotes, and slow mornings.',
    image: image('photo-1532372320572-cda25653f0f8'),
    monthlyPrice: 399,
    originalPrice: 699,
    rating: 4.8,
    reviewCount: 74,
    city: 'Ahmedabad',
    badge: 'Best Seller',
    badgeVariant: 'success',
    deposit: 1199,
    specifications: { Brand: 'RentEase Select', Dimensions: '42 × 22 × 16 in', Color: 'Natural oak', Condition: 'Like new', Warranty: '6 months' },
  }),
  makeProduct({
    id: 'nordic-queen-bed',
    name: 'Nordic Queen Bed',
    category: 'Bedroom',
    subcategory: 'Beds',
    description: 'A calm, upholstered bed frame with a supportive slatted base and softly rounded headboard.',
    image: image('photo-1505693416388-ac5ce068fe85'),
    monthlyPrice: 1299,
    originalPrice: 1899,
    rating: 4.8,
    reviewCount: 112,
    city: 'Mumbai',
    badge: 'Best Seller',
    badgeVariant: 'success',
    deposit: 3999,
    specifications: { Brand: 'RentEase Select', Dimensions: '63 × 84 × 42 in', Color: 'Oatmeal', Condition: 'Like new', Warranty: '6 months' },
  }),
  makeProduct({
    id: 'sleepwell-mattress',
    name: 'Sleepwell Comfort Mattress',
    category: 'Bedroom',
    subcategory: 'Mattresses',
    description: 'Medium-firm memory foam comfort with breathable layers for a better night’s sleep.',
    image: image('photo-1616486338812-3dadae4b4ace'),
    monthlyPrice: 899,
    originalPrice: 1299,
    rating: 4.7,
    reviewCount: 86,
    city: 'Pune',
    badge: 'New',
    badgeVariant: 'warning',
    deposit: 2499,
    specifications: { Brand: 'Sleepwell', Dimensions: '60 × 78 × 8 in', Color: 'White', Condition: 'New', Warranty: '12 months' },
  }),
  makeProduct({
    id: 'metro-dining-set',
    name: 'Metro Dining Set',
    category: 'Kitchen',
    subcategory: 'Dining',
    description: 'A compact four-seater dining set that brings a considered finish to everyday meals.',
    image: image('photo-1616486338812-3dadae4b4ace'),
    monthlyPrice: 999,
    originalPrice: 1399,
    rating: 4.8,
    reviewCount: 64,
    city: 'Pune',
    badge: 'Best Seller',
    badgeVariant: 'success',
    deposit: 2999,
    specifications: { Brand: 'RentEase Select', Dimensions: '48 × 30 × 30 in', Color: 'Walnut', Condition: 'Like new', Warranty: '6 months' },
  }),
  makeProduct({
    id: 'oak-bar-table',
    name: 'Oak Bar Table',
    category: 'Kitchen',
    subcategory: 'Dining',
    description: 'A slim bar-height table for breakfast, coffee, or an easy work-from-home perch.',
    image: image('photo-1519710164239-da123dc03ef4'),
    monthlyPrice: 749,
    originalPrice: 1099,
    rating: 4.6,
    reviewCount: 42,
    city: 'Delhi NCR',
    badge: 'Popular',
    badgeVariant: 'primary',
    deposit: 2299,
    specifications: { Brand: 'RentEase Select', Dimensions: '42 × 20 × 40 in', Color: 'Oak', Condition: 'Like new', Warranty: '6 months' },
  }),
  makeProduct({
    id: 'frostpro-refrigerator',
    name: 'FrostPro Refrigerator',
    category: 'Appliances',
    subcategory: 'Refrigerators',
    description: 'A spacious double-door refrigerator with practical storage for a well-stocked home.',
    image: image('photo-1571175443880-49e1d25b2bc5'),
    monthlyPrice: 1899,
    originalPrice: 2599,
    rating: 4.7,
    reviewCount: 108,
    city: 'Delhi NCR',
    badge: 'New',
    badgeVariant: 'warning',
    deposit: 5699,
    specifications: { Brand: 'FrostPro', Dimensions: '33 × 28 × 68 in', Color: 'Stainless steel', Condition: 'Like new', Warranty: '12 months' },
  }),
  makeProduct({
    id: 'aquawash-machine',
    name: 'AquaWash Machine',
    category: 'Appliances',
    subcategory: 'Washing Machines',
    description: 'An efficient front-load washer with gentle cycles and enough capacity for family laundry.',
    image: image('photo-1626806787461-102c1bfaaea1'),
    monthlyPrice: 1249,
    originalPrice: 1799,
    rating: 4.7,
    reviewCount: 91,
    city: 'Kolkata',
    badge: 'Featured',
    badgeVariant: 'primary',
    deposit: 3799,
    specifications: { Brand: 'AquaWash', Dimensions: '24 × 24 × 34 in', Color: 'Graphite', Condition: 'Like new', Warranty: '12 months' },
  }),
  makeProduct({
    id: 'quickheat-microwave',
    name: 'QuickHeat Microwave',
    category: 'Appliances',
    subcategory: 'Kitchen Appliances',
    description: 'A streamlined microwave for quick meals, reheating, and weeknight convenience.',
    image: image('photo-1585659722983-3a675dabf23d'),
    monthlyPrice: 549,
    originalPrice: 799,
    rating: 4.6,
    reviewCount: 53,
    city: 'Chennai',
    badge: 'Popular',
    badgeVariant: 'primary',
    deposit: 1699,
    specifications: { Brand: 'QuickHeat', Dimensions: '20 × 16 × 12 in', Color: 'Matte black', Condition: 'Like new', Warranty: '6 months' },
  }),
  makeProduct({
    id: 'breeze-air-purifier',
    name: 'Breeze Air Purifier',
    category: 'Appliances',
    subcategory: 'Air Care',
    description: 'Quiet, compact air care with a high-efficiency filter for fresher rooms around the clock.',
    image: image('photo-1585771724684-95c7a1c4c8c8'),
    monthlyPrice: 699,
    originalPrice: 999,
    rating: 4.6,
    reviewCount: 37,
    city: 'Bengaluru',
    badge: 'New',
    badgeVariant: 'warning',
    deposit: 1999,
    specifications: { Brand: 'Breeze', Dimensions: '10 × 10 × 22 in', Color: 'White', Condition: 'New', Warranty: '12 months' },
  }),
  makeProduct({
    id: 'workmate-laptop',
    name: 'WorkMate Laptop',
    category: 'Electronics',
    subcategory: 'Laptops',
    description: 'A lightweight laptop with all-day battery for work, study, and creative projects.',
    image: image('photo-1496181133206-80ce9b88a853'),
    monthlyPrice: 2499,
    originalPrice: 3299,
    rating: 4.9,
    reviewCount: 143,
    city: 'Hyderabad',
    badge: 'Featured',
    badgeVariant: 'primary',
    deposit: 7499,
    specifications: { Brand: 'WorkMate', Dimensions: '14-inch display', Color: 'Space grey', Condition: 'Like new', Warranty: '12 months' },
  }),
  makeProduct({
    id: 'viewpoint-monitor',
    name: 'Viewpoint 27-inch Monitor',
    category: 'Electronics',
    subcategory: 'Monitors',
    description: 'A crisp, colour-accurate display that gives focused work and gaming more room to breathe.',
    image: image('photo-1527443224154-c4a3942d3acf'),
    monthlyPrice: 1099,
    originalPrice: 1499,
    rating: 4.8,
    reviewCount: 87,
    city: 'Bengaluru',
    badge: 'Popular',
    badgeVariant: 'primary',
    deposit: 3299,
    specifications: { Brand: 'Viewpoint', Dimensions: '27-inch display', Color: 'Midnight black', Condition: 'Like new', Warranty: '12 months' },
  }),
  makeProduct({
    id: 'tabgo-tablet',
    name: 'TabGo Tablet',
    category: 'Electronics',
    subcategory: 'Tablets',
    description: 'A bright, portable tablet for reading, streaming, note-taking, and the commute home.',
    image: image('photo-1544244015-0df4b3ffc6b0'),
    monthlyPrice: 899,
    originalPrice: 1299,
    rating: 4.7,
    reviewCount: 66,
    city: 'Mumbai',
    badge: 'New',
    badgeVariant: 'warning',
    deposit: 2699,
    specifications: { Brand: 'TabGo', Dimensions: '10.2-inch display', Color: 'Silver', Condition: 'Like new', Warranty: '12 months' },
  }),
  makeProduct({
    id: 'pixelpro-phone',
    name: 'PixelPro Smartphone',
    category: 'Electronics',
    subcategory: 'Smartphones',
    description: 'A capable everyday smartphone with a vivid display, sharp camera, and 5G connectivity.',
    image: image('photo-1511707171634-5f897ff02aa9'),
    monthlyPrice: 1299,
    originalPrice: 1699,
    rating: 4.7,
    reviewCount: 59,
    city: 'Pune',
    badge: 'Popular',
    badgeVariant: 'primary',
    deposit: 3999,
    specifications: { Brand: 'PixelPro', Dimensions: '6.4-inch display', Color: 'Sage green', Condition: 'Like new', Warranty: '12 months' },
  }),
  makeProduct({
    id: 'playbox-console',
    name: 'PlayBox Console',
    category: 'Electronics',
    subcategory: 'Gaming',
    description: 'A living-room gaming setup for relaxed nights in, shared play, and immersive adventures.',
    image: image('photo-1606144042614-b2417e99c4e3'),
    monthlyPrice: 1599,
    originalPrice: 2199,
    rating: 4.8,
    reviewCount: 48,
    city: 'Chennai',
    badge: 'Popular',
    badgeVariant: 'primary',
    deposit: 4799,
    specifications: { Brand: 'PlayBox', Dimensions: 'Compact console', Color: 'Black', Condition: 'Like new', Warranty: '6 months' },
  }),
  makeProduct({
    id: 'ergo-desk-chair',
    name: 'Ergo Desk Chair',
    category: 'Office',
    subcategory: 'Chairs',
    description: 'Supportive lumbar comfort, breathable mesh, and adjustable height for long focused days.',
    image: image('photo-1580480055273-228ff5388ef8'),
    monthlyPrice: 749,
    originalPrice: 1099,
    rating: 4.6,
    reviewCount: 84,
    city: 'Chennai',
    badge: 'New',
    badgeVariant: 'warning',
    deposit: 2299,
    specifications: { Brand: 'Ergo', Dimensions: '26 × 26 × 42 in', Color: 'Charcoal', Condition: 'Like new', Warranty: '6 months' },
  }),
  makeProduct({
    id: 'focus-standing-desk',
    name: 'Focus Standing Desk',
    category: 'Office',
    subcategory: 'Desks',
    description: 'A clean sit-stand desk that makes it easy to change position and keep your day moving.',
    image: image('photo-1497366754035-f200968a6e72'),
    monthlyPrice: 1199,
    originalPrice: 1699,
    rating: 4.7,
    reviewCount: 51,
    city: 'Bengaluru',
    badge: 'Featured',
    badgeVariant: 'primary',
    deposit: 3599,
    specifications: { Brand: 'Focus', Dimensions: '48 × 24 in', Color: 'White oak', Condition: 'Like new', Warranty: '6 months' },
  }),
  makeProduct({
    id: 'papertrail-printer',
    name: 'PaperTrail Printer',
    category: 'Office',
    subcategory: 'Printers',
    description: 'A compact wireless printer for forms, study notes, creative work, and everyday admin.',
    image: image('photo-1612815154858-60aa4c59e7fe'),
    monthlyPrice: 599,
    originalPrice: 899,
    rating: 4.5,
    reviewCount: 31,
    city: 'Delhi NCR',
    badge: 'Popular',
    badgeVariant: 'primary',
    deposit: 1799,
    specifications: { Brand: 'PaperTrail', Dimensions: '17 × 13 × 7 in', Color: 'White', Condition: 'Like new', Warranty: '6 months' },
  }),
  makeProduct({
    id: 'modular-wardrobe',
    name: 'Modular Wardrobe',
    category: 'Bedroom',
    subcategory: 'Storage',
    description: 'Flexible wardrobe storage with a balanced mix of hanging space, shelves, and drawers.',
    image: image('photo-1558997519-83ea9252edf8'),
    monthlyPrice: 1099,
    originalPrice: 1599,
    rating: 4.6,
    reviewCount: 45,
    city: 'Mumbai',
    badge: 'Popular',
    badgeVariant: 'primary',
    deposit: 3299,
    specifications: { Brand: 'RentEase Select', Dimensions: '48 × 20 × 72 in', Color: 'Ash wood', Condition: 'Like new', Warranty: '6 months' },
  }),
  makeProduct({
    id: 'softline-bedside-table',
    name: 'Softline Bedside Table',
    category: 'Bedroom',
    subcategory: 'Tables',
    description: 'A compact bedside piece with a drawer for the small things that make a room feel settled.',
    image: image('photo-1594620302200-9a762244a156'),
    monthlyPrice: 399,
    originalPrice: 599,
    rating: 4.7,
    reviewCount: 38,
    city: 'Kolkata',
    badge: 'New',
    badgeVariant: 'warning',
    deposit: 1199,
    specifications: { Brand: 'RentEase Select', Dimensions: '18 × 16 × 22 in', Color: 'Natural oak', Condition: 'Like new', Warranty: '6 months' },
  }),
  makeProduct({
    id: 'halo-floor-lamp',
    name: 'Halo Floor Lamp',
    category: 'Furniture',
    subcategory: 'Lighting',
    description: 'A warm, architectural floor lamp that adds a softer glow to evenings and reading corners.',
    image: image('photo-1507473885765-e6ed057f782c'),
    monthlyPrice: 349,
    originalPrice: 499,
    rating: 4.6,
    reviewCount: 29,
    city: 'Hyderabad',
    badge: 'Popular',
    badgeVariant: 'primary',
    deposit: 999,
    specifications: { Brand: 'RentEase Select', Dimensions: '12 × 12 × 62 in', Color: 'Brushed brass', Condition: 'Like new', Warranty: '6 months' },
  }),
  makeProduct({
    id: 'smartvision-tv',
    name: 'SmartVision 55-inch TV',
    category: 'Electronics',
    subcategory: 'Televisions',
    description: 'A cinematic 4K display for film nights, sports, and the shows everyone is talking about.',
    image: image('photo-1593359677879-a4bb92f829d1'),
    monthlyPrice: 1799,
    originalPrice: 2499,
    rating: 4.8,
    reviewCount: 72,
    city: 'Hyderabad',
    badge: 'Featured',
    badgeVariant: 'primary',
    deposit: 5399,
    specifications: { Brand: 'SmartVision', Dimensions: '55-inch display', Color: 'Black', Condition: 'Like new', Warranty: '12 months' },
  }),
].map((product) => ({
  ...product,
  gallery: product.gallery?.length ? product.gallery : [product.image, product.image, product.image],
}));

export const PRODUCTS = [...CORE_PRODUCTS, ...generateExpandedProducts()];

export const FEATURED_PRODUCTS = PRODUCTS.slice(0, 8);

export const getProductById = (id) => PRODUCTS.find((product) => product.id === id);

export const getRelatedProducts = (product, limit = 4) =>
  PRODUCTS.filter((candidate) => candidate.id !== product.id && candidate.category === product.category).slice(0, limit);